spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000 #a day
      refresh-token:
        expiration: 604800000 #7 days

app-url: ${APP_URL}
weather-api:
    url: ${WEATHER_API_URL}
    key: ${WEATHER_API_KEY}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://10.92.96.3:5432/gofly
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/gofly
    username: ${DB_USERNAME}
    password: ${DB_USERNAME}

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: postgresql
