spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/gofly
    username: gofly
    password: gofly

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: postgresql