spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/gofly
    username: gofly
    password: gofly
    driverClassName: org.postgresql.Driver
