apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofly-api-deployment
  namespace: gofly-dev
spec:
  replicas: 1
  selector:
    app: gofly-api
  template:
    metadata:
      labels:
        app: gofly-api
    spec:
      containers:
        - name: gofly-api
          image: europe-west9-docker.pkg.dev/avian-foundy-3845513/docker-registry/gofly-api-0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILE_ACTIVE
              value: dev
