package fr.gofly.model.obstacle;

public enum ObstacleType {

    WIND_TURBINE,
    GROUP_OF_OBSTACLES_LIGHTED_AT_NIGHT_ABOVE_500_AGL,
    GROUP_OF_OBSTACLES_LIGHTED_AT_NIGHT_UNDER_500_AGL,
    GROUP_OF_OBSTACLES_NOT_LIGHTED_AT_NIGHT_UNDER_500_AGL,
    GROUP_OF_OBSTACLES_NOT_LIGHTED_AT_NIGHT_ABOVE_500_AGL,
    OBSTACLE_NOT_LIGHTED_AT_NIGHT_ABOVE_500_AGL,
    OBSTACLE_NOT_LIGHTED_AT_NIGHT_UNDER_500_AGL,
    OBSTACLE_LIGHTED_AT_NIGHT_ABOVE_500_AGL,
    OBSTACLE_LIGHTED_AT_NIGHT_UNDER_500_AGL
}
