name: Build, push to Artifact Registry and deploy in GKE

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch'
        required: true

env:
  REGION: ${{ vars.REGION }}
  CLUSTER: ${{ vars.CLUSTER }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Setup, Build, Publish and Deploy
    environment: dev
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch}}

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          token_format: 'access_token'

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven

      - name: Build with maven
        run: mvn clean package -pl ./gofly-api -am

      - id: docker-push-tagged
        name: Tag Docker image and push to Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: ./gofly-api
          push: true
          tags: |
            europe-west9-docker.pkg.dev/avian-foundry-384513/docker/gofly-api:latest

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ vars.CLUSTER }}
          location: ${{ vars.REGION }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy with Helm
        run: |
          helm upgrade --install gofly-api ./gofly-api/deploy/gofly-api -n gofly-dev